
DROP TABLE IF EXISTS villagers;
CREATE TABLE villagers(
name TEXT,
icon TEXT,
photo TEXT,
house TEXT,
species TEXT,
gender TEXT,
personality	TEXT,
subtype TEXT,
hobby TEXT,
birthday TEXT,
catchphrase	TEXT,
favorite_song TEXT,
favorite_saying	TEXT,
style_1	TEXT,
style_2	TEXT,
color_1	TEXT,
color_2	TEXT,
default_clothing TEXT,
default_umbrella TEXT,	
wallpaper TEXT,
flooring TEXT,
furniture_list TEXT,
furniture_name_list TEXT,
diy_workbench TEXT,
kitchen_equipment TEXT,
version_added VARCHAR(10),
name_color VARCHAR(15),
bubble_color VARCHAR(15),
filename VARCHAR(20),
unique_entry_id VARCHAR(50)
)

DROP TABLE IF EXISTS housewares;
CREATE TABLE housewares(
name TEXT,
image TEXT,
variation TEXT,
body_title TEXT,
pattern TEXT,
pattern_title TEXT,
diy	TEXT,
body_customize TEXT,
pattern_customize TEXT,
pattern_customize_options TEXT,
kit_cost TEXT,
kit_type TEXT,
cyrus_customize_price TEXT,
buy	TEXT,
sell INT,
color_1	TEXT,
color_2	TEXT,
size TEXT,
surface TEXT,	
exchange_price TEXT,
exchange_currency TEXT,
source TEXT,
souce_notes TEXT,
season_even TEXT,
season_event_exclusive TEXT,
hha_base INT,
hha_concept_1 TEXT,
hha_concept_2 TEXT,
hha_series TEXT,
hha_set TEXT,
hha_category TEXT,
interact TEXT,
tag TEXT,
outdoor TEXT,
speaker_type TEXT,
lighting_type TEXT,
catalog TEXT,
version_added TEXT,
unlocked TEXT,
filename TEXT,
variant_id TEXT,
internal_id INT,
unique_entry_id VARCHAR(30)
)

DROP TABLE IF EXISTS miscellaneous;
CREATE TABLE miscellaneous(
name TEXT,	
image TEXT,
variation TEXT,
body_title TEXT,
pattern TEXT,
pattern_title TEXT,
diy	TEXT,
body_customize TEXT,
pattern_customize TEXT,
pattern_customize_options TEXT,
stack_size TEXT,
kit_cost TEXT,
kit_type TEXT,
cyrus_customize_price TEXT,
buy	TEXT,
sell INT,
color_1	TEXT,
color_2	TEXT,
size TEXT,
surface TEXT,	
exchange_price TEXT,
exchange_currency TEXT,
source TEXT,
souce_notes TEXT,
season_event TEXT,
season_event_exclusive TEXT,
hha_base INT,
hha_concept_1 TEXT,
hha_concept_2 TEXT,
hha_series TEXT,
hha_set TEXT,
hha_category TEXT,
interact TEXT,
tag TEXT,
outdoor TEXT,
speaker_type TEXT,
lighting_type TEXT,
food_power TEXT,
catalog TEXT,
version_added TEXT,
unlocked TEXT,
filename TEXT,
variant_id TEXT,
internal_id INT,
unique_entry_id VARCHAR(30)
)

DROP TABLE IF EXISTS wall_mounted;
CREATE TABLE wall_mounted(
name TEXT,
image TEXT,
variation TEXT,
body_title TEXT,
pattern TEXT,
pattern_title TEXT,
diy	TEXT,
body_customize TEXT,
pattern_customize TEXT,
pattern_customize_options TEXT,
kit_cost TEXT,
kit_type TEXT,
cyrus_customize_price TEXT,
buy	TEXT,
sell INT,
color_1	TEXT,
color_2	TEXT,
exchange_price TEXT,
exchange_currency TEXT,
size TEXT,
source TEXT,
souce_notes TEXT,
season_event TEXT,
season_event_exclusive TEXT,
hha_base INT,
hha_concept_1 TEXT,
hha_concept_2 TEXT,
hha_series TEXT,
hha_set TEXT,
hha_category TEXT,
interact TEXT,
tag TEXT,
outdoor TEXT,
lighting_type TEXT,
door_decor TEXT,
catalog TEXT,
version_added TEXT,
unlocked TEXT,
filename TEXT,
variant_id TEXT,
internal_id INT,
unique_entry_id VARCHAR(30)
)

DROP TABLE IF EXISTS ceiling_decor;
CREATE TABLE ceiling_decor(
name TEXT,
image TEXT,
variation TEXT,
body_title TEXT,
pattern TEXT,
pattern_title TEXT,
diy	TEXT,
body_customize TEXT,
pattern_customize TEXT,
pattern_customize_options TEXT,
kit_cost TEXT,
kit_type TEXT,
cyrus_customize_price TEXT,
buy	TEXT,
sell INT,
color_1	TEXT,
color_2	TEXT,
exchange_price TEXT,
exchange_currency TEXT,
size TEXT,
source TEXT,
souce_notes TEXT,
season_event TEXT,
season_event_exclusive TEXT,
hha_base INT,
hha_concept_1 TEXT,
hha_concept_2 TEXT,
hha_series TEXT,
hha_set TEXT,
hha_category TEXT,
interact TEXT,
tag TEXT,
outdoor TEXT,
lighting_type TEXT,
catalog TEXT,
version_added TEXT,
unlocked TEXT,
filename TEXT,
variant_id TEXT,
internal_id INT,
unique_entry_id VARCHAR(30)
)

DROP TABLE IF EXISTS wallpaper;
CREATE TABLE wallpaper(
name TEXT,
image TEXT,
vfx TEXT,
vfx_type TEXT,
diy	TEXT,
buy	TEXT,
sell INT,
color_1	TEXT,
color_2	TEXT,
exchange_price TEXT,
exchange_currency TEXT,
source TEXT,
souce_notes TEXT,
season_event TEXT,
season_event_exclusive TEXT,
window_type TEXT,
window_color TEXT,
pane_type TEXT,
curtain_type TEXT,
curtain_color TEXT,
ceiling_type TEXT,
hha_base INT,
hha_concept_1 TEXT,
hha_concept_2 TEXT,
hha_series TEXT,
tag TEXT,
catalog TEXT,
version_added TEXT,
unlocked TEXT,
filename TEXT,
internal_id INT,
unique_entry_id VARCHAR(30)
)

DROP TABLE IF EXISTS floors;
CREATE TABLE floors(
name TEXT,
image TEXT,
vfx TEXT,
diy	TEXT,
buy	TEXT,
sell INT,
color_1	TEXT,
color_2	TEXT,
exchange_price TEXT,
exchange_currency TEXT,
source TEXT,
souce_notes TEXT,
season_event TEXT,
season_event_exclusive TEXT,
hha_base INT,
hha_concept_1 TEXT,
hha_concept_2 TEXT,
hha_series TEXT,
tag TEXT,
catalog TEXT,
version_added TEXT,
unlocked TEXT,
filename TEXT,
internal_id INT,
unique_entry_id VARCHAR(30)
)

DROP TABLE IF EXISTS rugs;
CREATE TABLE rugs(
name TEXT,
image TEXT,
diy	TEXT,
buy	TEXT,
sell INT,
color_1	TEXT,
color_2	TEXT,
size TEXT,
size_category TEXT,
exchange_price TEXT,
exchange_currency TEXT,
source TEXT,
souce_notes TEXT,
season_event TEXT,
season_event_exclusive TEXT,
hha_base INT,
hha_concept_1 TEXT,
hha_concept_2 TEXT,
hha_series TEXT,
tag TEXT,
catalog TEXT,
version_added TEXT,
unlocked TEXT,
filename TEXT,
internal_id INT,
unique_entry_id VARCHAR(30)
)

